#!/bin/bash
# Heavily inspiried by i3blocks-contrib/cpu_usage (aka I found out how they did it, and slightly customized the appearance).
IDLE=$(mpstat 1 1 | grep all | head -1 | rev | cut -f 1 -d ' ' | rev)
WARN=50
CRITICAL=75
CPU_USAGE=$(echo "100 - $IDLE" | bc)
echo "$CPU_USAGE%"
echo ""
if (( $(echo "$CPU_USAGE > $CRITICAL" | bc) )); then
    echo "#FF0000"
elif(( $(echo "$CPU_USAGE > $WARN" | bc) )); then
    echo "#FFFC00"
fi
exit 0
