#!/bin/sh
DIR="/"
WARNING_THRESH=75

LOCAL_FLAG="-l"
if [ "$1" = "-n" ] || [ "$2" = "-n" ]; then
    LOCAL_FLAG=""
fi

df -h -P -l "$DIR" | awk -v label="$LABEL" -v thresh=$WARNING_THRESH '
/\/.*/ {
    print $5
    if(int($5) > thresh) {
        print
        print "#FF0000"
    }
	exit 0
}
'
