#!/bin/bash
SSID=$(nmcli -t -f active,ssid dev wifi | egrep '^yes' | cut -d : -f2)
CONNECTED=$(nmcli -t -f active,ssid dev wifi | egrep '^yes' | head -1)

echo $SSID
echo
if [ -z $CONNECTED ]; then
    echo "#660000"
else
    echo "#006600"
fi
