--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/nathan/dotfiles/wallpapers/wallpaper_repo/painted-blue-mountains.jpg"

-- Special
background="#371a10"
foreground="#cfe1e3"
cursor="#cfe1e3"

-- Colors
color0="#371a10"
color1="#5CA1AF"
color2="#73B8C5"
color3="#77C3CD"
color4="#9FB3B4"
color5="#91BBC6"
color6="#8FCAD2"
color7="#cfe1e3"
color8="#909d9e"
color9="#5CA1AF"
color10="#73B8C5"
color11="#77C3CD"
color12="#9FB3B4"
color13="#91BBC6"
color14="#8FCAD2"
color15="#cfe1e3"
