# Shell variables
# Generated by 'wal'
wallpaper='/home/nathan/dotfiles/wallpapers/wallpaper_repo/stones-water.jpg'

# Special
background='#121516'
foreground='#cadde3'
cursor='#cadde3'

# Colors
color0='#121516'
color1='#C58F6A'
color2='#4E7A85'
color3='#687F80'
color4='#61969F'
color5='#559EAD'
color6='#95A1A5'
color7='#cadde3'
color8='#8d9a9e'
color9='#C58F6A'
color10='#4E7A85'
color11='#687F80'
color12='#61969F'
color13='#559EAD'
color14='#95A1A5'
color15='#cadde3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
