# Shell variables
# Generated by 'wal'
wallpaper='/home/nathan/.wallpapers/wallpaper_repo/mountainlake_reflection.jpg'

# Special
background='#071F1E'
foreground='#dfe3e9'
cursor='#dfe3e9'

# Colors
color0='#071F1E'
color1='#93A8B0'
color2='#C1C6B2'
color3='#97B7CA'
color4='#B1C7D8'
color5='#B9CEE0'
color6='#D0D6E1'
color7='#dfe3e9'
color8='#9c9ea3'
color9='#93A8B0'
color10='#C1C6B2'
color11='#97B7CA'
color12='#B1C7D8'
color13='#B9CEE0'
color14='#D0D6E1'
color15='#dfe3e9'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
