# Shell variables
# Generated by 'wal'
wallpaper='/home/nathan/dotfiles/wallpapers/wallpaper_repo/painted-blue-mountains.jpg'

# Special
background='#371a10'
foreground='#cfe1e3'
cursor='#cfe1e3'

# Colors
color0='#371a10'
color1='#5CA1AF'
color2='#73B8C5'
color3='#77C3CD'
color4='#9FB3B4'
color5='#91BBC6'
color6='#8FCAD2'
color7='#cfe1e3'
color8='#909d9e'
color9='#5CA1AF'
color10='#73B8C5'
color11='#77C3CD'
color12='#9FB3B4'
color13='#91BBC6'
color14='#8FCAD2'
color15='#cfe1e3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
