--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/nathan/dotfiles/wallpapers/wallpaper_repo/mountainlake_reflection.jpg"

-- Special
background="#031414"
foreground="#dfe3e9"
cursor="#dfe3e9"

-- Colors
color0="#031414"
color1="#7DAAC1"
color2="#94A8B0"
color3="#97B7CA"
color4="#B1C7D8"
color5="#B9CEE0"
color6="#D0D6E1"
color7="#dfe3e9"
color8="#9c9ea3"
color9="#7DAAC1"
color10="#94A8B0"
color11="#97B7CA"
color12="#B1C7D8"
color13="#B9CEE0"
color14="#D0D6E1"
color15="#dfe3e9"
