--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/nathan/dotfiles/wallpapers/wallpaper_repo/stones-water.jpg"

-- Special
background="#121516"
foreground="#cadde3"
cursor="#cadde3"

-- Colors
color0="#121516"
color1="#C58F6A"
color2="#4E7A85"
color3="#687F80"
color4="#61969F"
color5="#559EAD"
color6="#95A1A5"
color7="#cadde3"
color8="#8d9a9e"
color9="#C58F6A"
color10="#4E7A85"
color11="#687F80"
color12="#61969F"
color13="#559EAD"
color14="#95A1A5"
color15="#cadde3"
